### PR TITLE
update readme.md to add myself as a member

### PR DESCRIPTION
**Pull request by chengjingtao**
Signed-off-by: jtcheng <jtcheng@alauda.io>

### CODE REVIEW

**Comment by afrittoli** [comment]
Welcome @chengjingtao and thank you for your PR!

It would be great to know more about your interest in the CDF Events SIG - you're welcome to join the [CDF Slack](https://join.slack.com/t/cdeliveryfdn/shared_invite/zt-ao8y4qhd-BQcTUg5l7m0HxXyBvJrT4w%20) and jump into the [#sig-events channel](https://cdeliveryfdn.slack.com/archives/C0151BTKEJX) to introduce yourself and tell us more :)

**Comment by chengjingtao** [comment]
@afrittoli Thanks for your response. 
I don't have an email with these domain suffixes list by  [CDF Slack](https://join.slack.com/t/cdeliveryfdn/shared_invite/zt-ao8y4qhd-BQcTUg5l7m0HxXyBvJrT4w%20)  and my email address is jtcheng0616@gmail.com.
Could you send me an invitation link ?

**Comment by afrittoli** [comment]
> @afrittoli Thanks for your response.
> I don't have an email with these domain suffixes list by [CDF Slack](https://join.slack.com/t/cdeliveryfdn/shared_invite/zt-ao8y4qhd-BQcTUg5l7m0HxXyBvJrT4w%20) and my email address is [jtcheng0616_at_gmail.com](mailto:jtcheng0616@gmail.com).
> Could you send me an invitation link ?

@chengjingtao since you have a gmail account, you can use the "Continue with google" button
image

**Comment by chengjingtao** [comment]
> > @afrittoli Thanks for your response.
> > I don't have an email with these domain suffixes list by [CDF Slack](https://join.slack.com/t/cdeliveryfdn/shared_invite/zt-ao8y4qhd-BQcTUg5l7m0HxXyBvJrT4w%20) and my email address is [jtcheng0616_at_gmail.com](mailto:jtcheng0616@gmail.com).
> > Could you send me an invitation link ?
> 
> @chengjingtao since you have a gmail account, you can use the "Continue with google" button
> image

it doesn't work.   It prompts that I was forbidden because my email suffix is not in the domain list. 
I will give some screenshot when I arrived home.

**Comment by m-linner-ericsson** [comment]
@chengjingtao I have sent you an invitation.

**Comment by chengjingtao** [comment]
> @chengjingtao I have sent you an invitation.

Thank you so much.   I join the channel now.

**Comment by e-backmark-ericsson** [comment]
No response on the last question for over a year. Closing this PR.

**Pull request closed without merging**
