### PR TITLE
add to participants list

### PR DESCRIPTION
**Pull request by sbtaylor15**

### CODE REVIEW

**Comment by erkist** [comment]
I looked in the SIG Interoperability repo, they have members listed on the following format:

First Last (@github-id), Company.

I think we should do the same.

**Comment by afrittoli** [comment]
> I looked in the SIG Interoperability repo, they have members listed on the following format:
> 
> First Last (@github-id), Company.
> 
> I think we should do the same.

Yeah, it sounds good. I think we have the same in the old repo - so it will be like that once I copy it over.

**Comment by sbtaylor15** [comment]
Updated to follow the format that is PR https://github.com/cdfoundation/sig-events/pull/1.

Let me know if that is correct.

**Review by afrittoli — APPROVED** [review]
Thank you!

**Pull request merged**
