### PR TITLE
Add Unittests

### PR DESCRIPTION
**Pull request by m-linner-ericsson**
Add unit tests for all events and commands.

I am not an expert in Go so any suggestions on best practices are welcome!

Signed-off-by: Mattias Linner <mattias.linner@ericsson.com>

### CODE REVIEW

**Comment by Rubix982** [comment]
I'm learning `golang` these days as well, so completely new to it, but apart from `go`, I think this is a very big PR since it adds a lot of LoCs in a single commit and that made me take some time to go through the PR.

Other than that, from a maintainability perspective, maybe we can add links in each of the unit tests as a comment referring to the events they test against.

**Comment by m-linner-ericsson** [comment]
@Rubix982 Yes we should have added the unit tests when the code was written but that was not the case... I am no expert in go so if you have any ideas how to improve it please give suggestions

As I am writing the test I might be blind but I thought the naming of the test was sufficient to link the test to what they test. Do you have any good example for such a "link"?

**Comment by Rubix982** [comment]
The code looks good to me. I do not have suggestions regarding it.

My apologies, I realized GitHub links against functions automatically, so there is no need for "links".

**Review by erkist — APPROVED** [review]
Not versed in Go, but looks good!

**Comment by e-backmark-ericsson** [comment]
The revamped Go SDK in cdevents org has unit tests added to it now, so this issue can be closed

**Pull request closed without merging**
